(()=>{
  const state={industry:'Services & agencies',solution:'Website',goal:'Look premium'};
  const finder=document.createElement('section');finder.className='solution-finder';finder.id='solution-finder';
  const steps=[['industry','01 / YOUR BUSINESS','What kind of business are you?', ['Hospitality & travel','Wellness & fitness','Clinics & health','Services & agencies','Events & celebrations']],['solution','02 / WHAT TO BUILD','What would make the biggest difference?', ['Website','Booking & reservation','Business system','AI & automation']],['goal','03 / YOUR GOAL','What outcome matters most right now?', ['Get more enquiries','Save team time','Organize operations','Look premium']]];
  finder.innerHTML=`<div class="finder-heading"><div><p class="eyebrow">07 / Build your solution</p><h2>Not sure what<br>to build <em>first?</em></h2></div><p>Choose what fits your business. NEXORA will prepare the right starting point for your project—before our first conversation.</p></div><div class="finder-shell"><div class="finder-steps">${steps.map(([key,number,title,options])=>`<div class="finder-step" data-step="${key}"><p>${number}</p><h3>${title}</h3><div class="choice-row">${options.map(option=>`<button type="button" class="choice ${state[key]===option?'selected':''}" data-value="${option}">${option}</button>`).join('')}</div></div>`).join('')}</div><aside class="finder-result"><div><p class="eyebrow">YOUR NEXORA DIRECTION</p><h3></h3><p></p></div><div><button type="button">Continue with this plan <b>↗</b></button><div class="finder-note">Your choices are added to the project brief. No commitment required.</div></div></aside></div>`;
  document.querySelector('.pricing').insertAdjacentElement('afterend',finder);
  const result=finder.querySelector('.finder-result'),profiles={Website:['Premium business website','A strong, responsive website designed to create trust and turn visits into quality enquiries.'], 'Booking & reservation':['Booking & reservation experience','A clear digital journey for availability, reservations and customer requests.'], 'Business system':['Business management system','A structured workspace for clients, operations, planning and visibility.'], 'AI & automation':['AI & automation workflow','A smarter process that reduces repetitive work and connects the tools your business uses.']};
  const render=()=>{const [title,description]=profiles[state.solution];result.querySelector('h3').textContent=title;result.querySelector('p:not(.eyebrow)').textContent=description};render();
  finder.querySelectorAll('.choice').forEach(button=>button.addEventListener('click',()=>{const step=button.closest('.finder-step').dataset.step;state[step]=button.dataset.value;button.closest('.choice-row').querySelectorAll('.choice').forEach(item=>item.classList.toggle('selected',item===button));render()}));
  result.querySelector('button').addEventListener('click',()=>{const typeMap={Website:'Website','Booking & reservation':'Web Application','Business system':'Business Management System','AI & automation':'AI / Automation'};const select=document.querySelector('[name="project_type"]');if(select)select.value=typeMap[state.solution];const message=document.querySelector('[name="message"]');if(message)message.value=`Business: ${state.industry}\nPriority: ${state.solution}\nGoal: ${state.goal}\n\n`;document.querySelector('#contact').scrollIntoView({behavior:'smooth',block:'start'})});
})();
