const menu=document.querySelector('.menu'), nav=document.querySelector('.nav nav');
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.textContent=open?'Close':'Menu'});
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.textContent='Menu'}));
const form=document.getElementById('project-form'),status=document.createElement('p'),submitButton=form.querySelector('button');
status.className='form-status wide';status.setAttribute('role','status');status.setAttribute('aria-live','polite');form.querySelector('.form-note').before(status);form.querySelector('.form-note').textContent='Your request is securely sent directly to NEXORA.';
form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));status.className='form-status wide';status.textContent='Sending your project request…';submitButton.disabled=true;try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'We could not send your request.');status.classList.add('success');status.textContent='Thanks — your project request has been sent. We’ll be in touch soon.';form.reset()}catch(error){if(error.message.includes('Email delivery is being configured.')){status.classList.add('success');status.textContent='Sending securely…';window.setTimeout(()=>form.submit(),250);return}status.classList.add('error');status.textContent=error.message||'Something went wrong. Please email us directly.'}finally{submitButton.disabled=false}});
const projectCards=[
  ['dropstudio.png','DropStudio','Fashion e-commerce','An editorial online store with a high-end visual identity and conversion-focused product discovery.'],
  ['dentalflow.png','DentalFlow','Clinic management','A complete dentist dashboard for patients, appointments, treatment plans and follow-up.'],
  ['archora.png','Archora','Architecture workspace','A professional workspace for architecture studios to centralize projects, clients and site progress.'],
  ['travel.png','Travel Agency Platform','Travel / Tourism','A polished tourism experience designed around discovery, services and bookings.'],
  ['gym.png','Gym Management System','Fitness / Management','A digital product for memberships, client operations and business administration.'],
  ['portfolio.png','Business Portfolio Website','Business website','A sharp, responsive presence built to present work clearly and turn interest into enquiries.']
  ,['plan-events.png','Plan Events','Event planning platform','A refined event planning experience for discovering services, inspiration and celebration ideas.']
];
const showcase=document.createElement('section');showcase.className='proof-gallery';showcase.setAttribute('aria-labelledby','proof-gallery-title');showcase.innerHTML=`<div class="proof-intro"><p class="eyebrow">02B / Product proof</p><h2 id="proof-gallery-title">Real interfaces.<br><em>Real business value.</em></h2><p>Selected NEXORA builds shown as visual product previews. Each one is designed to turn a business workflow into a polished digital experience.</p></div><div class="proof-grid">${projectCards.map(([image,title,type,description],index)=>`<article class="proof-card"><div class="proof-image"><img src="assets/projects/${image}" alt="${title} interface preview" loading="lazy"><span>0${index+1}</span></div><div class="proof-copy"><p>${type}</p><h3>${title}</h3><small>${description}</small><b>Built for business</b></div></article>`).join('')}</div></section>`;
showcase.querySelectorAll('.proof-card').forEach((card,index)=>card.id=`project-shot-${projectCards[index][0].replace('.png','')}`);
showcase.querySelectorAll('.proof-image span').forEach(badge=>badge.textContent='LIVE PREVIEW');
document.querySelector('.projects').insertAdjacentElement('afterend',showcase);
const previewMap={travel:'travel',gym:'gym',portfolio:'portfolio',event:'dropstudio'};
const experienceScript=document.createElement('script');experienceScript.src='experience.js';document.body.append(experienceScript);
const finderScript=document.createElement('script');finderScript.src='finder.js';document.body.append(finderScript);
document.querySelectorAll('.project').forEach(project=>{const key=Object.keys(previewMap).find(name=>project.classList.contains(name));const link=project.querySelector('.project-info a');if(!key||!link)return;const button=document.createElement('button');button.type='button';button.className='preview-button';button.innerHTML='View screenshots <b>↓</b>';button.setAttribute('aria-label',`View screenshots for ${project.querySelector('h3').textContent}`);button.addEventListener('click',()=>document.getElementById(`project-shot-${previewMap[key]}`)?.scrollIntoView({behavior:'smooth',block:'center'}));link.replaceWith(button)});
